# Default WebSeed Configuration

scraping:
  default_mode: basic # basic, advanced, or super
  timeout: 30 # Request timeout in seconds
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

output:
  default_format: markdown # markdown, tagged, or img
  default_path: null # If null, uses current working directory

rate_limiting:
  requests_per_minute: 10 # Default rate limit
  domain_specific:
    github.com: 5
    youtube.com: 3
    instagram.com: 5

logging:
  level: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: null # If null, logs only to console
